name: Publish Project

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
   
    - name: Restore dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src -c Release --no-restore
      
    - name: Create Nuget Package
      run: dotnet pack -c Release /p:Version=${{github.event.release.tag_name}} /p:PackageReleaseNotes="See https://github.com/ShaharPrishMSFT/SubtleEngineering/releases/tag/${{github.event.release.tag_name}}" ./src/SubtleEngineering.Analyzers

    - name: Archive Nuget Package for Project
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: "./src/SubtleEngineering.Analyzers/bin/Release/SubtleEngineering.Analyzers.${{github.event.release.tag_name}}.nupkg"

    - name: Publish Nuget Package
      run: dotnet nuget push ./src/**/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

      
